---
abstract: 'Package documentation generator'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  File::Copy::Recursive: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-DocKnot
provides:
  App::DocKnot:
    file: lib/App/DocKnot.pm
    version: '3.00'
  App::DocKnot::Command:
    file: lib/App/DocKnot/Command.pm
    version: '3.00'
  App::DocKnot::Config:
    file: lib/App/DocKnot/Config.pm
    version: '3.00'
  App::DocKnot::Dist:
    file: lib/App/DocKnot/Dist.pm
    version: '3.00'
  App::DocKnot::Generate:
    file: lib/App/DocKnot/Generate.pm
    version: '3.00'
requires:
  File::BaseDir: '0'
  File::ShareDir: '1.00'
  IPC::Run: '0'
  IPC::System::Simple: '0'
  JSON: '0'
  Perl6::Slurp: '0'
  Template: '0'
  perl: '5.024'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=App-DocKnot
  homepage: https://www.eyrie.org/~eagle/software/docknot
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/rra/docknot.git
version: '3.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
