---
abstract: 'Package documentation generator'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  File::Copy::Recursive: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-DocKnot
provides:
  App::DocKnot:
    file: lib/App/DocKnot.pm
    version: '7.01'
  App::DocKnot::Command:
    file: lib/App/DocKnot/Command.pm
    version: '7.01'
  App::DocKnot::Config:
    file: lib/App/DocKnot/Config.pm
    version: '7.01'
  App::DocKnot::Dist:
    file: lib/App/DocKnot/Dist.pm
    version: '7.01'
  App::DocKnot::Generate:
    file: lib/App/DocKnot/Generate.pm
    version: '7.01'
  App::DocKnot::Release:
    file: lib/App/DocKnot/Release.pm
    version: '7.01'
  App::DocKnot::Spin:
    file: lib/App/DocKnot/Spin.pm
    version: '7.01'
  App::DocKnot::Spin::Pointer:
    file: lib/App/DocKnot/Spin/Pointer.pm
    version: '7.01'
  App::DocKnot::Spin::RSS:
    file: lib/App/DocKnot/Spin/RSS.pm
    version: '7.01'
  App::DocKnot::Spin::Sitemap:
    file: lib/App/DocKnot/Spin/Sitemap.pm
    version: '7.01'
  App::DocKnot::Spin::Thread:
    file: lib/App/DocKnot/Spin/Thread.pm
    version: '7.01'
  App::DocKnot::Spin::Versions:
    file: lib/App/DocKnot/Spin/Versions.pm
    version: '7.01'
  App::DocKnot::Update:
    file: lib/App/DocKnot/Update.pm
    version: '7.01'
  App::DocKnot::Util:
    file: lib/App/DocKnot/Util.pm
    version: '7.01'
requires:
  Date::Parse: '0'
  File::BaseDir: '0'
  File::ShareDir: '1.00'
  Git::Repository: '0'
  IO::Compress::Xz: '0'
  IO::Uncompress::Gunzip: '0'
  IPC::Run: '0'
  IPC::System::Simple: '0'
  Image::Size: '0'
  JSON::MaybeXS: '0'
  Kwalify: '0'
  List::SomeUtils: '0.07'
  Path::Iterator::Rule: '0'
  Path::Tiny: '0.101'
  Perl6::Slurp: '0'
  Pod::Thread: '3.01'
  Sort::Versions: '0'
  Template: '0'
  YAML::XS: '0.81'
  perl: '5.024'
resources:
  bugtracker: https://github.com/rra/docknot/issues
  homepage: https://www.eyrie.org/~eagle/software/docknot
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/rra/docknot.git
version: '7.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
